# Levy's Yazi

[mgr]
ratio          = [ 3, 6, 9 ] # ratios [back | current dir | preview] 0 disables
linemode       = "size"      # Options: none, size, btime, mtime, permissions, owner
sort_by        = "size"
sort_dir_first = true
sort_reverse   = true
show_hidden    = true
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll", "drag" ]

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 1000
max_height      = 1000
image_quality   = 90

[input]
cursor_blink = true

