# ===========================================================================
# Levy's Hyprpaper 
# ===========================================================================
wallpaper {
    monitor = 
    path = ~/Wallpapers/ayanami.png
    fit_mode = cover
}

# Disable message on bottom of screen (why do that? like really why?)
splash = false 

