##################################################################################################
# Levy's btop++
##################################################################################################
# Visual 
truecolor   = true
force_tty   = false
color_theme = "eldritch"
theme_background = true

# Presets 
disable_presets = "Off"
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"

# General Options1
update_ms           = 1000
vim_keys            = true
terminal_sync       = true
disable_mouse       = false
rounded_corners     = true
background_update   = true
save_config_on_exit = false
log_level           = "WARNING"
shown_boxes         = "cpu mem net proc"

# Graphs 
#* Default symbols: "braille", "block" or "tty".
graph_symbol      = "braille"
graph_symbol_cpu  = "default"
graph_symbol_gpu  = "default"
graph_symbol_mem  = "default"
graph_symbol_net  = "default"
graph_symbol_proc = "default"

# Proccess Tab
#* Processes sorting: "pid" "program" "arguments" "threads" "user" "memory" "cpu lazy" "cpu direct",
proc_sorting         = "cpu lazy"
proc_left            = false
proc_tree            = false
proc_colors          = true
proc_reversed        = false
proc_gradient        = false
proc_per_core        = false
proc_mem_bytes       = true
proc_aggregate       = true
proc_cpu_graphs      = false
proc_info_smaps      = false
proc_filter_kernel   = true
proc_follow_detailed = true
keep_dead_proc_usage = false

# CPU Tabs
freq_mode        = "range"
temp_scale       = "celsius"
cpu_sensor       = "Auto"
show_gpu_info    = "Auto"
cpu_graph_upper  = "total"
cpu_graph_lower  = "total"
cpu_core_map     = ""
custom_cpu_name  = ""
clock_format     = "/host"
cpu_bottom       = false
show_uptime      = true
base_10_sizes    = true
show_cpu_freq    = true
check_temp       = true
show_coretemp    = true
show_cpu_watts   = true
cpu_invert_lower = true
cpu_single_graph = false

# Memory and Disk Tab
disks_filter         = "/ /mnt/HardDrive"
mem_graphs           = false
mem_below_net        = false
zfs_arc_cached       = true
swap_disk            = false
show_swap            = true
show_disks           = true
only_physical        = true
use_fstab            = true
zfs_hide_datasets    = false
disk_free_priv       = false
show_io_stat         = false
io_mode              = false
io_graph_speeds      = ""
io_graph_combined    = false
swap_upload_download = false

# Network Tab
net_upload      = 100
net_download    = 100
net_auto        = true
net_sync        = false
net_iface       = ""
base_10_bitrate = "True"

# Baterry Tab
show_battery       = false
selected_battery   = "Auto"
show_battery_watts = true

# GPU Tab
shown_gpus               = "nvidia amd intel"
gpu_mirror_graph         = true
custom_gpu_name0         = ""
custom_gpu_name1         = ""
custom_gpu_name2         = ""
custom_gpu_name3         = ""
custom_gpu_name4         = ""
custom_gpu_name5         = ""
nvml_measure_pcie_speeds = true
rsmi_measure_pcie_speeds = false

