# Kitty theme settings

# Author: Microsoft.
# Theme name: Campbell.
# Blurb: The default theme of Microsoft's terminals, including Windows Terminal and cmd.

# General Colors
cursor                          #ffffff
foreground                      #cccccc
background                      #0c0c0c
selection_background            #ffffff

# The basic 16 colors
# Black
color0 #0c0c0c
color8 #767676

# Red
color1 #c50f1f
color9 #e74856

# Green
color2  #13a10e
color10 #16c60c

# Yellow
color3  #f19c00
color11 #f9f1a5

# Blue
color4  #0037da
color12 #3b78ff

# Magenta
color5  #881798
color13 #b4009e

# Cyan
color6  #3a96dd
color14 #61d6d6

# White
color7  #cccccc
color15 #f2f2f2

# Tab Style
active_tab_foreground   #444444
active_tab_background   #ffffff
inactive_tab_foreground #cccccc
inactive_tab_background #0a0a0a

