#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#                       Settings

#####################################################
# Font
#####################################################
font_family                 JetBrainsMono Nerd Font
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   15

#####################################################
# Cursor
#####################################################
# Trail (measured in ms, if color is set to none it uses cursor color)
cursor_trail                0
cursor_trail_color          none 

# Shape: Options include (beam, block & underline)
cursor_shape                beam 

# Blinking:
cursor_blink_interval       0.4
#cursor_stop_blinking_after 1

#####################################################
# Window
#####################################################
# Size
remember_window_size        no
initial_window_width        78c
initial_window_height       20c

# Transparency 
background_blur             0
background_opacity          1.0
dynamic_background_opacity  yes

# Padding
window_padding_width         4
single_window_padding_width -1

#####################################################
# Tab bars
#####################################################
tab_bar_edge        bottom
tab_bar_align       left

# Possible styles: angled, slanted and round.
tab_bar_style       powerline
tab_powerline_style slanted
tab_bar_min_tabs    2

#####################################################
# QOL
#####################################################
scrollbar                   scrolled
scrollback_lines            10000
enable_audio_bell           no
hide_window_decorations     no
copy_on_select              yes

#####################################################
# Colors
#####################################################
include current-theme.conf

